services:
  gazebo-sim:
    build:
      context: .
      dockerfile: Dockerfile_gazebo
    image: my-ros2-jazzy-desktop-full:latest
    container_name: gazebo-sim
    networks:
      - ros-net
    ipc: host
    environment:
      - ROS_DOMAIN_ID=0
      - DISPLAY=${DISPLAY}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - GZ_SIM_RESOURCE_PATH=/models
    volumes:
      - ${X11_SOCKET_MOUNT:-/tmp/.X11-unix:/tmp/.X11-unix:rw}
      - ${WSLG_MOUNT:-/dev/null:/dev/null}
      - ./worlds:/worlds
      - ./models:/models
    devices:
      - ${DXG_DEVICE:-/dev/null}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: gz sim -v 4 -r /worlds/drone_world.sdf
    tty: true
    stdin_open: true

  drone:
    build:
      context: .
      dockerfile: Dockerfile_drone
    networks:
      - ros-net
    ipc: host
    volumes:
      - ./shared:/shared
      - ./models:/models
    environment:
      - ROS_DOMAIN_ID=0
      - GZ_SIM_RESOURCE_PATH=/models
    tty: true
    stdin_open: true

networks:
  ros-net:
    driver: bridge