FROM osrf/ros:jazzy-desktop-full

# Download Gazebo Sim (Harmonic) and the bridge for ROS2 Jazzy
RUN apt-get update && apt-get install -y \
    ros-jazzy-ros-gz \
    && rm -rf /var/lib/apt/lists/*

# In Jazzy, the official command is 'gz sim'
CMD ["gz", "sim", "-v", "4", "-r", "empty.sdf"]