FROM ros:jazzy-ros-base

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
        ros-jazzy-ros-gz-sim \
        ros-jazzy-ros-gz-bridge \
        python3-pip \
        iproute2 \
        iputils-ping \
        netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /entrypoint /drone_ws

COPY entrypoints/entrypoint_drone.sh /entrypoint/entrypoint_drone.sh
RUN chmod +x /entrypoint/entrypoint_drone.sh
COPY drone_agent/drone_agent_wrapper.py /drone_ws/drone_agent_wrapper.py

WORKDIR /drone_ws

ENTRYPOINT ["/entrypoint/entrypoint_drone.sh"]
